"""TradingView live-chart data source for TradingAgents.

(C) Generated by Claude. Programmatic Python interface to the TradingView MCP
`tv` CLI, which reads the user's running TradingView Desktop chart over the
Chrome DevTools Protocol.

Unlike the vendor data sources in this package (yfinance, alpha_vantage), this
is a single live source tied to whatever chart is open in TradingView, so it is
intentionally NOT registered in the interface.py vendor-fallback router. Import
the functions directly:

    from tradingagents.dataflows.tradingview import get_quote, get_ohlcv

Requirements:
  - TradingView Desktop running with the CDP debug port (port 9222).
  - The `tv` CLI on PATH, or the tradingview-mcp checkout reachable via the
    TRADINGVIEW_MCP_DIR env var (defaults to ~/tradingview-mcp).

Env overrides:
  - TRADINGVIEW_CLI:     full path to a `tv`-compatible CLI entry point.
  - TRADINGVIEW_MCP_DIR: directory of the tradingview-mcp checkout.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any, Optional

DEFAULT_MCP_DIR = Path.home() / "tradingview-mcp"
DEFAULT_TIMEOUT = 30


class TradingViewError(RuntimeError):
    """Raised when the `tv` CLI fails or returns an error payload."""


def _resolve_command() -> list[str]:
    """Build the base command used to invoke the TradingView CLI.

    Resolution order: TRADINGVIEW_CLI env -> `tv` on PATH -> node + the cli
    entry point inside TRADINGVIEW_MCP_DIR (or ~/tradingview-mcp).
    """
    explicit = os.environ.get("TRADINGVIEW_CLI")
    if explicit:
        return [_node(), explicit] if explicit.endswith(".js") else [explicit]

    on_path = shutil.which("tv")
    if on_path:
        return [on_path]

    mcp_dir = Path(os.environ.get("TRADINGVIEW_MCP_DIR", DEFAULT_MCP_DIR))
    cli_entry = mcp_dir / "src" / "cli" / "index.js"
    if not cli_entry.is_file():
        raise TradingViewError(
            f"TradingView CLI not found. Install `tv` globally or set "
            f"TRADINGVIEW_MCP_DIR (looked for {cli_entry})."
        )
    return [_node(), str(cli_entry)]


def _node() -> str:
    node = shutil.which("node")
    if not node:
        raise TradingViewError("`node` not found on PATH; required to run the TradingView CLI.")
    return node


def tv_command(*args: str, timeout: int = DEFAULT_TIMEOUT) -> Any:
    """Run an arbitrary `tv` subcommand and return its parsed JSON output.

    Example: tv_command("ohlcv", "-n", "50") == get_ohlcv(count=50)

    Raises TradingViewError on non-zero exit, timeout, or unparseable output.
    """
    cmd = _resolve_command() + [str(a) for a in args]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except subprocess.TimeoutExpired as exc:
        raise TradingViewError(f"`tv {' '.join(args)}` timed out after {timeout}s") from exc

    if proc.returncode != 0:
        # The CLI prints a JSON error payload to stderr on failure.
        detail = proc.stderr.strip() or proc.stdout.strip()
        try:
            payload = json.loads(detail)
            detail = payload.get("error", detail)
        except (json.JSONDecodeError, AttributeError):
            pass
        raise TradingViewError(f"`tv {' '.join(args)}` failed (exit {proc.returncode}): {detail}")

    out = proc.stdout.strip()
    if not out:
        return None
    try:
        return json.loads(out)
    except json.JSONDecodeError as exc:
        raise TradingViewError(f"Could not parse `tv {' '.join(args)}` output: {out[:200]}") from exc


def get_status() -> dict:
    """Return CDP connection status and the currently open chart (symbol, resolution)."""
    return tv_command("status")


def get_quote(symbol: Optional[str] = None) -> dict:
    """Return the real-time price quote for `symbol`, or the active chart's symbol if omitted."""
    return tv_command("quote", symbol) if symbol else tv_command("quote")


def get_ohlcv(count: int = 100, summary: bool = False) -> dict:
    """Return OHLCV bars for the active chart.

    Args:
        count: number of bars (default 100, CLI max 500).
        summary: if True, return summary statistics instead of every bar.
    """
    args = ["ohlcv", "-n", str(count)]
    if summary:
        args.append("-s")
    return tv_command(*args)


def get_indicator_values() -> dict:
    """Return current indicator values from the chart's data window."""
    return tv_command("values")


if __name__ == "__main__":
    # Smoke test against the live TradingView session.
    print(json.dumps(get_status(), indent=2))
    print(json.dumps(get_quote(), indent=2))
