"""LangChain agent tools for live TradingView chart data.

(C) Generated by Claude. Wraps tradingagents.dataflows.tradingview so analyst
agents can read the user's running TradingView Desktop session during a run.

Important: `get_live_chart_bars` and `get_live_chart_indicators` reflect
WHATEVER chart is currently open in TradingView (the underlying CLI has no
per-symbol parameter for them). `get_live_chart_quote` can target a specific
symbol. Tools return readable strings and never raise, so a closed TradingView
or lost connection degrades gracefully instead of breaking the agent graph.
"""

import json
from typing import Annotated

from langchain_core.tools import tool

from tradingagents.dataflows.tradingview import (
    TradingViewError,
    get_indicator_values,
    get_ohlcv,
    get_quote,
)


@tool
def get_live_chart_quote(
    symbol: Annotated[
        str,
        "Optional exchange-qualified symbol, e.g. CME_MINI:NQ1! or NASDAQ:AAPL. "
        "Leave empty to read the symbol currently open in TradingView.",
    ] = "",
) -> str:
    """
    Get a real-time price quote from the live TradingView Desktop session.

    Use this for the latest live price/last/volume when intraday freshness
    matters more than the historical OHLCV vendors. Reflects the user's running
    TradingView app, not a historical API.

    Args:
        symbol (str): Exchange-qualified symbol, or empty for the active chart.
    Returns:
        str: JSON with symbol, open/high/low/close, last, volume, exchange.
    """
    try:
        return json.dumps(get_quote(symbol or None), indent=2)
    except TradingViewError as e:
        return f"Live TradingView quote unavailable: {e}"


@tool
def get_live_chart_bars(
    count: Annotated[int, "Number of recent bars to summarize (1-500)"] = 100,
    summary: Annotated[
        bool, "True for summary stats (low token cost); False for every bar"
    ] = True,
) -> str:
    """
    Get recent OHLCV bars from the chart currently open in TradingView Desktop.

    NOTE: This reads the ACTIVE chart's symbol and resolution (timeframe) as set
    in the TradingView app — it cannot target a different symbol. Confirm the
    chart symbol with get_live_chart_quote (no args) before relying on these
    bars for a specific instrument.

    Args:
        count (int): Number of recent bars (default 100, max 500).
        summary (bool): Summary stats vs. full bar list (default True).
    Returns:
        str: JSON of bar data or summary statistics for the active chart.
    """
    try:
        return json.dumps(get_ohlcv(count=count, summary=summary), indent=2)
    except TradingViewError as e:
        return f"Live TradingView bars unavailable: {e}"


@tool
def get_live_chart_indicators() -> str:
    """
    Get current indicator values from the data window of the chart open in
    TradingView Desktop (e.g. the EMAs, RSI, MACD the user has applied).

    NOTE: Reflects the ACTIVE chart only — both its symbol and the specific
    studies the user has loaded. There is no symbol or indicator parameter.

    Returns:
        str: JSON listing each loaded study and its current values.
    """
    try:
        return json.dumps(get_indicator_values(), indent=2)
    except TradingViewError as e:
        return f"Live TradingView indicators unavailable: {e}"


def live_chart_snapshot(bar_count: int = 20) -> str:
    """Compact, prompt-ready snapshot of the live TradingView chart.

    For single-shot agents (trader, risk debators) that have no tool-calling
    loop: embed this directly in the prompt. Combines the active chart's quote,
    a recent-bar summary, and applied indicator values. Never raises — returns
    an "unavailable" note on failure so prompts degrade gracefully.

    The snapshot leads with the chart's symbol so the agent can confirm it
    matches the instrument under analysis before relying on it.
    """
    try:
        quote = get_quote()
    except TradingViewError as e:
        return f"[Live TradingView chart unavailable: {e}]"

    symbol = quote.get("symbol", "unknown") if isinstance(quote, dict) else "unknown"
    parts = [
        f"Live TradingView chart symbol: {symbol}",
        "Quote: " + json.dumps(quote),
    ]
    try:
        parts.append("Recent bars (summary): " + json.dumps(get_ohlcv(count=bar_count, summary=True)))
    except TradingViewError as e:
        parts.append(f"Recent bars unavailable: {e}")
    try:
        parts.append("Applied indicators: " + json.dumps(get_indicator_values()))
    except TradingViewError as e:
        parts.append(f"Applied indicators unavailable: {e}")
    return "\n".join(parts)
